name: Find inactive collaborators

on:
  schedule:
    - cron: "0 0 1 * *" # Runs at 00:00 UTC on the 1st day of every month

  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  find:
    if: github.repository == 'nodejs/web-team'
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          egress-policy: audit

      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Report inactive collaborators
        id: inactive
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            const { default: report } = await import("${{github.workspace}}/.github/scripts/inactive-collaborator-report.mjs");
            report(github, context);
